export const categoryOverviewPages = [
  {
    slug: "pop-painting-vadodara",
    metaTitle: "POP & Painting Contractor in Vadodara | False Ceiling & Wall Painting",
    metaDescription: "Professional POP false ceiling & painting services in Vadodara. Expert wall painting, texture paint, gypsum ceiling & POP work. Call +91 93139 82980",
    config: {
      title: "POP & Painting Services",
      heroTitle: "Best POP & Painting Services in Vadodara",
      heroDescription: "Transform your home with expert POP false ceiling and professional painting services. Quality work at affordable prices.",
      category: "painting" as const,
      features: [
        "POP False Ceiling Design", "Gypsum False Ceiling", "Interior Wall Painting", "Exterior Painting",
        "Texture Painting", "POP Work & Finishing", "Wall Putty & Primer", "Asian Paints Application",
        "Berger Paints Application", "Enamel Painting", "Distemper & Emulsion", "POP Cornice Design",
      ],
      process: [
        { step: 1, title: "Site Visit", description: "Free measurement & consultation" },
        { step: 2, title: "Quotation", description: "Detailed estimate provided" },
        { step: 3, title: "Preparation", description: "Surface preparation & primer" },
        { step: 4, title: "Execution", description: "Professional painting & finishing" },
      ],
      faqs: [
        { question: "What is the cost of wall painting per sq.ft in Vadodara?", answer: "Interior wall painting costs ₹12-18 per sq.ft including wall preparation, primer, and two coats of paint. Premium paints like Asian Paints Royale cost ₹18-25 per sq.ft." },
        { question: "How long does painting a 2BHK flat take?", answer: "A 2BHK flat (approx 800-1000 sq.ft) takes 4-6 days for complete painting including putty, primer, and two coats. We ensure proper drying between coats." },
        { question: "What is POP false ceiling cost per sq.ft?", answer: "POP false ceiling costs ₹75-120 per sq.ft and Gypsum false ceiling costs ₹85-140 per sq.ft including design, material, and installation." },
        { question: "Do you use branded paints only?", answer: "Yes, we use only branded paints from Asian Paints, Berger, Nerolac, and Dulux. We show you the paint containers before starting work." },
        { question: "Is there warranty on painting work?", answer: "Yes, we provide 1-year warranty on all painting work. Premium paints come with manufacturer warranty of 3-5 years against discoloration." },
      ],
      relatedServices: [
        { name: "False Ceiling", href: "/false-ceiling-vadodara" },
        { name: "Texture Painting", href: "/texture-painting-vadodara" },
        { name: "Wall Painting", href: "/wall-painting-vadodara" },
        { name: "POP Work", href: "/pop-work-vadodara" },
        { name: "Gypsum Ceiling", href: "/gypsum-false-ceiling-vadodara" },
        { name: "Exterior Painting", href: "/exterior-painting-vadodara" },
        { name: "Asian Paints", href: "/asian-paints-contractor-vadodara" },
        { name: "Wall Putty", href: "/wall-putty-vadodara" },
      ],
      areas: [
        { name: "Alkapuri", href: "/painting-alkapuri-vadodara" }, { name: "Gotri", href: "/painting-gotri-vadodara" },
        { name: "Manjalpur", href: "/painting-manjalpur-vadodara" }, { name: "Akota", href: "/painting-akota-vadodara" },
        { name: "Bhayli", href: "/painting-bhayli-vadodara" }, { name: "Karelibaug", href: "/painting-karelibaug-vadodara" },
        { name: "Waghodia Road", href: "/painting-waghodia-vadodara" }, { name: "Makarpura", href: "/painting-makarpura-vadodara" },
        { name: "Chhani", href: "/painting-chhani-vadodara" }, { name: "Harni", href: "/painting-harni-vadodara" },
        { name: "Fatehgunj", href: "/painting-fatehgunj-vadodara" }, { name: "Gorwa", href: "/painting-gorwa-vadodara" },
      ],
    },
  },
  {
    slug: "plumbing-vadodara",
    metaTitle: "Plumber in Vadodara | Best Plumbing Services Near You",
    metaDescription: "Professional plumber services in Vadodara. Expert pipe fitting, bathroom fitting, leak repair, drainage cleaning & more. 24/7 service. Call +91 93139 82980",
    config: {
      title: "Plumbing Services",
      heroTitle: "Best Plumbing Services in Vadodara",
      heroDescription: "Expert plumbers for all your plumbing needs. Pipe fitting, bathroom renovation, leak repair, and 24/7 emergency services.",
      category: "plumbing" as const,
      features: [
        "24/7 Emergency Plumbing", "Pipe Fitting & Repair", "Bathroom Fitting", "Tap Installation & Repair",
        "Water Tank Installation", "Drainage Cleaning", "Leak Detection & Repair", "Geyser Installation",
        "Water Pump Repair", "Toilet Installation", "Kitchen Sink Fitting", "Water Line Connection",
      ],
      process: [
        { step: 1, title: "Book Service", description: "Call or WhatsApp us" },
        { step: 2, title: "Inspection", description: "Our plumber inspects the issue" },
        { step: 3, title: "Quote", description: "Transparent pricing shared" },
        { step: 4, title: "Repair", description: "Quick and quality repair" },
      ],
      faqs: [
        { question: "Do you provide 24/7 emergency plumbing service?", answer: "Yes, we provide 24/7 emergency plumbing services in Vadodara for pipe bursts, leaks, blocked drains, and other urgent issues. Our plumber reaches within 30-60 minutes." },
        { question: "What is the visiting charge for plumber in Vadodara?", answer: "Our visiting charge is ₹200 which is adjustable against the work done. For emergency night calls, there may be additional charges." },
        { question: "Can you fix concealed pipe leaks?", answer: "Yes, we have expertise in detecting and fixing concealed pipe leaks using advanced techniques. We ensure minimal wall damage during repair." },
        { question: "Do you install water purifiers?", answer: "Yes, we install all types of water purifiers including RO, UV, and gravity-based systems. We also provide AMC for water purifiers." },
        { question: "How much does bathroom fitting cost?", answer: "Complete bathroom fitting including taps, shower, toilet fitting costs ₹2,500-5,000 depending on the number of fittings and complexity." },
      ],
      relatedServices: [
        { name: "Pipe Fitting", href: "/pipe-fitting-vadodara" }, { name: "Bathroom Fitting", href: "/bathroom-fitting-vadodara" },
        { name: "Water Tank", href: "/water-tank-vadodara" }, { name: "Drainage Cleaning", href: "/drainage-cleaning-vadodara" },
        { name: "Leak Repair", href: "/leak-repair-vadodara" }, { name: "Geyser Installation", href: "/geyser-installation-vadodara" },
        { name: "Tap Repair", href: "/tap-repair-vadodara" }, { name: "Water Pump", href: "/water-pump-vadodara" },
      ],
      areas: [
        { name: "Alkapuri", href: "/plumber-alkapuri-vadodara" }, { name: "Gotri", href: "/plumber-gotri-vadodara" },
        { name: "Manjalpur", href: "/plumber-manjalpur-vadodara" }, { name: "Akota", href: "/plumber-akota-vadodara" },
        { name: "Bhayli", href: "/plumber-bhayli-vadodara" }, { name: "Karelibaug", href: "/plumber-karelibaug-vadodara" },
        { name: "Waghodia Road", href: "/plumber-waghodia-vadodara" }, { name: "Makarpura", href: "/plumber-makarpura-vadodara" },
        { name: "Chhani", href: "/plumber-chhani-vadodara" }, { name: "Harni", href: "/plumber-harni-vadodara" },
        { name: "Fatehgunj", href: "/plumber-fatehgunj-vadodara" }, { name: "Gorwa", href: "/plumber-gorwa-vadodara" },
      ],
    },
  },
  {
    slug: "solar-vadodara",
    metaTitle: "Solar Panel Installation in Vadodara | Solar System for Home",
    metaDescription: "Professional solar panel installation in Vadodara. On-grid & off-grid solar systems with government subsidy. 25-year warranty. Call +91 93139 82980",
    config: {
      title: "Solar Installation Services",
      heroTitle: "Best Solar Panel Installation in Vadodara",
      heroDescription: "Go green with solar energy. Professional installation with government subsidy assistance. Save up to 90% on electricity bills.",
      category: "solar" as const,
      features: [
        "On-Grid Solar System", "Off-Grid Solar System", "Hybrid Solar System", "Rooftop Solar Installation",
        "Solar Panel Cleaning", "Solar Inverter Installation", "Net Metering Setup", "Government Subsidy Assistance",
        "Solar Battery Installation", "Solar Water Heater", "Solar Street Light", "Solar System AMC",
      ],
      process: [
        { step: 1, title: "Site Survey", description: "Rooftop assessment & load analysis" },
        { step: 2, title: "Design", description: "System design & quotation" },
        { step: 3, title: "Installation", description: "Professional panel installation" },
        { step: 4, title: "Net Metering", description: "DISCOM approval & commissioning" },
      ],
      faqs: [
        { question: "What is the cost of 3kW solar system in Vadodara?", answer: "A 3kW on-grid solar system costs ₹1,40,000-1,60,000 before subsidy. After PM Surya Ghar Yojana subsidy of ₹43,764, the effective cost is around ₹1,00,000-1,20,000." },
        { question: "How much electricity does solar panel generate?", answer: "In Vadodara, 1kW solar system generates approximately 4-5 units per day or 120-150 units per month. A 3kW system can power a typical home completely." },
        { question: "What is PM Surya Ghar solar subsidy?", answer: "Under PM Surya Ghar Yojana, you get ₹14,588 subsidy for 1kW, ₹29,176 for 2kW, and ₹43,764 for 3kW or above rooftop solar system. We handle complete subsidy paperwork." },
        { question: "What is the warranty on solar panels?", answer: "Solar panels come with 25-year performance warranty (80% output guaranteed). Inverters have 5-year warranty. We provide free service for 1 year after installation." },
        { question: "Do you help with net metering approval?", answer: "Yes, we handle complete net metering process including GUVNL application, meter installation, and DISCOM approval. This takes 2-4 weeks after installation." },
      ],
      relatedServices: [
        { name: "On-Grid Solar", href: "/on-grid-solar-vadodara" }, { name: "Off-Grid Solar", href: "/off-grid-solar-vadodara" },
        { name: "Solar Subsidy", href: "/solar-subsidy-vadodara" }, { name: "Solar Panel Cleaning", href: "/solar-panel-cleaning-vadodara" },
        { name: "Solar Inverter", href: "/solar-inverter-vadodara" }, { name: "Net Metering", href: "/net-metering-vadodara" },
        { name: "Solar Battery", href: "/solar-battery-vadodara" }, { name: "Rooftop Solar", href: "/rooftop-solar-vadodara" },
      ],
      areas: [
        { name: "Alkapuri", href: "/solar-alkapuri-vadodara" }, { name: "Gotri", href: "/solar-gotri-vadodara" },
        { name: "Manjalpur", href: "/solar-manjalpur-vadodara" }, { name: "Akota", href: "/solar-akota-vadodara" },
        { name: "Bhayli", href: "/solar-bhayli-vadodara" }, { name: "Karelibaug", href: "/solar-karelibaug-vadodara" },
        { name: "Waghodia Road", href: "/solar-waghodia-vadodara" }, { name: "Makarpura", href: "/solar-makarpura-vadodara" },
        { name: "Chhani", href: "/solar-chhani-vadodara" }, { name: "Harni", href: "/solar-harni-vadodara" },
        { name: "Fatehgunj", href: "/solar-fatehgunj-vadodara" }, { name: "Gorwa", href: "/solar-gorwa-vadodara" },
      ],
    },
  },
];
