// All service keywords and areas data - Expanded for SEO (370+ keywords)

// ============ PAINTING & POP KEYWORDS (70+) ============
export const paintingKeywords = [
  // POP & Ceiling
  { slug: "pop-false-ceiling-vadodara", title: "POP False Ceiling", description: "Professional POP false ceiling contractors" },
  { slug: "false-ceiling-design-vadodara", title: "False Ceiling Design", description: "Creative false ceiling design services" },
  { slug: "gypsum-false-ceiling-vadodara", title: "Gypsum False Ceiling", description: "Expert gypsum board ceiling installation" },
  { slug: "pop-work-vadodara", title: "POP Work", description: "Quality POP work and finishing" },
  { slug: "pop-contractor-vadodara", title: "POP Contractor", description: "Experienced POP contractors" },
  { slug: "pop-cornice-design-vadodara", title: "POP Cornice Design", description: "Decorative POP cornice work" },
  { slug: "led-false-ceiling-vadodara", title: "LED False Ceiling", description: "False ceiling with LED lighting" },
  { slug: "pvc-ceiling-vadodara", title: "PVC Ceiling", description: "PVC ceiling panel installation" },
  { slug: "wooden-ceiling-vadodara", title: "Wooden Ceiling", description: "Wooden false ceiling design" },
  { slug: "metal-ceiling-vadodara", title: "Metal Ceiling", description: "Metal false ceiling installation" },
  { slug: "coffered-ceiling-vadodara", title: "Coffered Ceiling", description: "Coffered ceiling design" },
  { slug: "tray-ceiling-vadodara", title: "Tray Ceiling", description: "Tray ceiling installation" },
  { slug: "false-ceiling-price-vadodara", title: "False Ceiling Price", description: "Affordable false ceiling rates" },
  { slug: "pop-ceiling-cost-vadodara", title: "POP Ceiling Cost", description: "POP ceiling pricing" },
  { slug: "bedroom-false-ceiling-vadodara", title: "Bedroom False Ceiling", description: "Bedroom ceiling design" },
  { slug: "living-room-ceiling-vadodara", title: "Living Room Ceiling", description: "Living room ceiling work" },
  { slug: "office-false-ceiling-vadodara", title: "Office False Ceiling", description: "Office ceiling installation" },
  { slug: "hall-false-ceiling-vadodara", title: "Hall False Ceiling", description: "Hall ceiling design" },
  { slug: "kitchen-false-ceiling-vadodara", title: "Kitchen False Ceiling", description: "Kitchen ceiling work" },
  { slug: "best-pop-contractor-vadodara", title: "Best POP Contractor", description: "Top rated POP contractors" },
  { slug: "pop-design-vadodara", title: "POP Design", description: "Latest POP designs" },
  { slug: "false-ceiling-near-me-vadodara", title: "False Ceiling Near Me", description: "Local ceiling contractors" },
  // Wall Painting
  { slug: "wall-painting-vadodara", title: "Wall Painting", description: "Professional wall painting services" },
  { slug: "interior-painting-vadodara", title: "Interior Painting", description: "Interior wall painting experts" },
  { slug: "exterior-painting-vadodara", title: "Exterior Painting", description: "Exterior painting and weather coating" },
  { slug: "texture-painting-vadodara", title: "Texture Painting", description: "Decorative texture painting" },
  { slug: "house-painting-vadodara", title: "House Painting", description: "Complete house painting services" },
  { slug: "room-painting-vadodara", title: "Room Painting", description: "Single room painting service" },
  { slug: "office-painting-vadodara", title: "Office Painting", description: "Commercial office painting" },
  { slug: "commercial-painting-vadodara", title: "Commercial Painting", description: "Commercial building painting" },
  { slug: "painting-contractor-vadodara", title: "Painting Contractor", description: "Professional painting contractors" },
  { slug: "painters-vadodara", title: "Painters", description: "Skilled painters for all work" },
  { slug: "wall-putty-vadodara", title: "Wall Putty", description: "Wall putty application" },
  { slug: "primer-work-vadodara", title: "Primer Work", description: "Primer and base coat work" },
  { slug: "distemper-painting-vadodara", title: "Distemper Painting", description: "Distemper paint application" },
  { slug: "emulsion-painting-vadodara", title: "Emulsion Painting", description: "Emulsion paint services" },
  { slug: "enamel-painting-vadodara", title: "Enamel Painting", description: "Enamel paint for doors/windows" },
  { slug: "wall-texture-vadodara", title: "Wall Texture", description: "Wall texture design" },
  { slug: "stucco-painting-vadodara", title: "Stucco Painting", description: "Stucco texture finish" },
  { slug: "velvet-texture-vadodara", title: "Velvet Texture", description: "Velvet texture painting" },
  { slug: "metallic-paint-vadodara", title: "Metallic Paint", description: "Metallic wall painting" },
  { slug: "designer-painting-vadodara", title: "Designer Painting", description: "Designer wall painting" },
  { slug: "3d-wall-painting-vadodara", title: "3D Wall Painting", description: "3D wall art painting" },
  { slug: "spray-painting-vadodara", title: "Spray Painting", description: "Spray painting services" },
  { slug: "epoxy-painting-vadodara", title: "Epoxy Painting", description: "Epoxy floor painting" },
  { slug: "anti-fungal-painting-vadodara", title: "Anti Fungal Painting", description: "Anti-fungal wall treatment" },
  { slug: "damp-proof-painting-vadodara", title: "Damp Proof Painting", description: "Damp proof coating" },
  // Brand Keywords
  { slug: "asian-paints-contractor-vadodara", title: "Asian Paints Contractor", description: "Authorized Asian Paints applicator" },
  { slug: "berger-paints-contractor-vadodara", title: "Berger Paints Contractor", description: "Berger Paints application expert" },
  { slug: "nerolac-paints-vadodara", title: "Nerolac Paints", description: "Nerolac paint services" },
  { slug: "dulux-paints-vadodara", title: "Dulux Paints", description: "Dulux paint application" },
  { slug: "asian-paints-royale-vadodara", title: "Asian Paints Royale", description: "Royale paint application" },
  { slug: "asian-paints-apex-vadodara", title: "Asian Paints Apex", description: "Apex exterior painting" },
  { slug: "indigo-paints-vadodara", title: "Indigo Paints", description: "Indigo paint services" },
  // Price & Near Me
  { slug: "painting-price-vadodara", title: "Painting Price", description: "Competitive painting rates" },
  { slug: "painting-cost-per-sqft-vadodara", title: "Painting Cost Per Sqft", description: "Per sqft painting rates" },
  { slug: "cheap-painters-vadodara", title: "Cheap Painters", description: "Affordable painting services" },
  { slug: "painting-rates-vadodara", title: "Painting Rates", description: "Current painting rates" },
  { slug: "best-painters-vadodara", title: "Best Painters", description: "Top rated painters" },
  { slug: "professional-painters-vadodara", title: "Professional Painters", description: "Expert painting team" },
  { slug: "painting-near-me-vadodara", title: "Painting Near Me", description: "Local painters nearby" },
  { slug: "home-painting-vadodara", title: "Home Painting", description: "Complete home painting" },
  { slug: "flat-painting-vadodara", title: "Flat Painting", description: "Apartment painting service" },
  { slug: "villa-painting-vadodara", title: "Villa Painting", description: "Villa painting services" },
  { slug: "bungalow-painting-vadodara", title: "Bungalow Painting", description: "Bungalow painting work" },
];

// ============ CIVIL WORK KEYWORDS (70+) ============
export const civilKeywords = [
  { slug: "civil-contractors-vadodara", title: "Civil Contractors", description: "Professional civil contractors" },
  { slug: "tile-fitting-vadodara", title: "Tile Fitting", description: "Expert tile fitting services" },
  { slug: "floor-tile-fitting-vadodara", title: "Floor Tile Fitting", description: "Floor tile installation" },
  { slug: "wall-tile-fitting-vadodara", title: "Wall Tile Fitting", description: "Wall tile installation" },
  { slug: "bathroom-tile-work-vadodara", title: "Bathroom Tile Work", description: "Bathroom tiling services" },
  { slug: "kitchen-tile-work-vadodara", title: "Kitchen Tile Work", description: "Kitchen tile installation" },
  { slug: "marble-fitting-vadodara", title: "Marble Fitting", description: "Marble flooring installation" },
  { slug: "granite-fitting-vadodara", title: "Granite Fitting", description: "Granite fitting services" },
  { slug: "flooring-vadodara", title: "Flooring", description: "All types of flooring work" },
  { slug: "vitrified-tile-fitting-vadodara", title: "Vitrified Tile Fitting", description: "Vitrified tile work" },
  { slug: "italian-marble-vadodara", title: "Italian Marble", description: "Italian marble installation" },
  { slug: "kota-stone-vadodara", title: "Kota Stone", description: "Kota stone flooring" },
  { slug: "natural-stone-flooring-vadodara", title: "Natural Stone Flooring", description: "Natural stone work" },
  { slug: "tiles-contractor-vadodara", title: "Tiles Contractor", description: "Tiles work contractor" },
  { slug: "kajaria-tiles-vadodara", title: "Kajaria Tiles", description: "Kajaria tiles fitting" },
  { slug: "somany-tiles-vadodara", title: "Somany Tiles", description: "Somany tiles installation" },
  { slug: "johnson-tiles-vadodara", title: "Johnson Tiles", description: "Johnson tiles work" },
  { slug: "ceramic-tile-vadodara", title: "Ceramic Tile", description: "Ceramic tile fitting" },
  { slug: "porcelain-tile-vadodara", title: "Porcelain Tile", description: "Porcelain tile work" },
  { slug: "mosaic-tile-vadodara", title: "Mosaic Tile", description: "Mosaic tile installation" },
  { slug: "outdoor-tiles-vadodara", title: "Outdoor Tiles", description: "Outdoor tile fitting" },
  { slug: "parking-tiles-vadodara", title: "Parking Tiles", description: "Parking area tiles" },
  { slug: "elevation-tiles-vadodara", title: "Elevation Tiles", description: "Building elevation tiles" },
  { slug: "waterproofing-vadodara", title: "Waterproofing", description: "Waterproofing solutions" },
  { slug: "terrace-waterproofing-vadodara", title: "Terrace Waterproofing", description: "Terrace waterproofing treatment" },
  { slug: "bathroom-waterproofing-vadodara", title: "Bathroom Waterproofing", description: "Bathroom waterproofing" },
  { slug: "roof-waterproofing-vadodara", title: "Roof Waterproofing", description: "Roof waterproofing services" },
  { slug: "basement-waterproofing-vadodara", title: "Basement Waterproofing", description: "Basement waterproofing" },
  { slug: "tank-waterproofing-vadodara", title: "Tank Waterproofing", description: "Water tank waterproofing" },
  { slug: "waterproofing-cost-vadodara", title: "Waterproofing Cost", description: "Waterproofing rates" },
  { slug: "dr-fixit-waterproofing-vadodara", title: "Dr Fixit Waterproofing", description: "Dr Fixit products" },
  { slug: "sika-waterproofing-vadodara", title: "Sika Waterproofing", description: "Sika waterproofing" },
  { slug: "injection-grouting-vadodara", title: "Injection Grouting", description: "Injection grouting services" },
  { slug: "water-leakage-solution-vadodara", title: "Water Leakage Solution", description: "Leakage treatment" },
  { slug: "seepage-treatment-vadodara", title: "Seepage Treatment", description: "Seepage solution" },
  { slug: "bathroom-renovation-vadodara", title: "Bathroom Renovation", description: "Complete bathroom renovation" },
  { slug: "kitchen-renovation-vadodara", title: "Kitchen Renovation", description: "Kitchen renovation services" },
  { slug: "plastering-vadodara", title: "Plastering", description: "Wall plastering work" },
  { slug: "masonry-vadodara", title: "Masonry", description: "Expert masonry services" },
  { slug: "brick-work-vadodara", title: "Brick Work", description: "Brick construction work" },
  { slug: "rcc-construction-vadodara", title: "RCC Construction", description: "RCC concrete construction" },
  { slug: "building-contractor-vadodara", title: "Building Contractor", description: "Building construction contractor" },
  { slug: "house-construction-vadodara", title: "House Construction", description: "House construction services" },
  { slug: "compound-wall-vadodara", title: "Compound Wall", description: "Compound wall construction" },
  { slug: "boundary-wall-vadodara", title: "Boundary Wall", description: "Boundary wall construction" },
  { slug: "renovation-contractor-vadodara", title: "Renovation Contractor", description: "Home renovation contractor" },
  { slug: "civil-work-vadodara", title: "Civil Work", description: "All civil work services" },
  { slug: "construction-vadodara", title: "Construction", description: "Construction services" },
  { slug: "home-renovation-vadodara", title: "Home Renovation", description: "Complete home renovation" },
  { slug: "flat-renovation-vadodara", title: "Flat Renovation", description: "Apartment renovation" },
  { slug: "office-renovation-vadodara", title: "Office Renovation", description: "Office renovation work" },
  { slug: "shop-renovation-vadodara", title: "Shop Renovation", description: "Shop renovation services" },
  { slug: "building-repair-vadodara", title: "Building Repair", description: "Building repair work" },
  { slug: "structural-repair-vadodara", title: "Structural Repair", description: "Structural repair services" },
  { slug: "crack-repair-vadodara", title: "Crack Repair", description: "Wall crack repair" },
  { slug: "concrete-repair-vadodara", title: "Concrete Repair", description: "Concrete repair work" },
  { slug: "demolition-vadodara", title: "Demolition", description: "Demolition services" },
  { slug: "slab-work-vadodara", title: "Slab Work", description: "Concrete slab construction" },
  { slug: "foundation-work-vadodara", title: "Foundation Work", description: "Foundation construction" },
  { slug: "kadiya-kam-vadodara", title: "Kadiya Kam", description: "Mason work services" },
  { slug: "best-civil-contractor-vadodara", title: "Best Civil Contractor", description: "Top civil contractors" },
  { slug: "civil-work-near-me-vadodara", title: "Civil Work Near Me", description: "Local civil contractors" },
];

// ============ PLUMBING KEYWORDS (60+) ============
export const plumbingKeywords = [
  { slug: "plumbers-vadodara", title: "Plumbers", description: "Professional plumbers" },
  { slug: "plumbing-services-vadodara", title: "Plumbing Services", description: "Complete plumbing services" },
  { slug: "pipe-fitting-vadodara", title: "Pipe Fitting", description: "Pipe fitting and installation" },
  { slug: "water-leak-repair-vadodara", title: "Water Leak Repair", description: "Water leak detection and repair" },
  { slug: "drainage-work-vadodara", title: "Drainage Work", description: "Drainage installation and repair" },
  { slug: "tap-installation-vadodara", title: "Tap Installation", description: "Tap and faucet installation" },
  { slug: "faucet-repair-vadodara", title: "Faucet Repair", description: "Faucet repair services" },
  { slug: "bathroom-plumbing-vadodara", title: "Bathroom Plumbing", description: "Bathroom plumbing work" },
  { slug: "kitchen-plumbing-vadodara", title: "Kitchen Plumbing", description: "Kitchen plumbing services" },
  { slug: "pipeline-repair-vadodara", title: "Pipeline Repair", description: "Pipeline repair work" },
  { slug: "sewage-line-vadodara", title: "Sewage Line", description: "Sewage line work" },
  { slug: "drainage-cleaning-vadodara", title: "Drainage Cleaning", description: "Drainage cleaning service" },
  { slug: "cp-fitting-vadodara", title: "CP Fitting", description: "CP fitting installation" },
  { slug: "sanitary-work-vadodara", title: "Sanitary Work", description: "Sanitary installation" },
  { slug: "plumber-near-me-vadodara", title: "Plumber Near Me", description: "Local plumber nearby" },
  { slug: "emergency-plumber-vadodara", title: "Emergency Plumber", description: "24/7 emergency plumber" },
  { slug: "24-hour-plumber-vadodara", title: "24 Hour Plumber", description: "24 hour plumbing service" },
  { slug: "best-plumber-vadodara", title: "Best Plumber", description: "Top rated plumbers" },
  { slug: "cheap-plumber-vadodara", title: "Cheap Plumber", description: "Affordable plumbing" },
  { slug: "geyser-repair-vadodara", title: "Geyser Repair", description: "Water heater repair" },
  { slug: "geyser-installation-vadodara", title: "Geyser Installation", description: "Geyser installation services" },
  { slug: "water-heater-repair-vadodara", title: "Water Heater Repair", description: "Water heater service" },
  { slug: "instant-geyser-vadodara", title: "Instant Geyser", description: "Instant geyser installation" },
  { slug: "storage-geyser-vadodara", title: "Storage Geyser", description: "Storage geyser service" },
  { slug: "solar-water-heater-repair-vadodara", title: "Solar Water Heater Repair", description: "Solar water heater service" },
  { slug: "bajaj-geyser-repair-vadodara", title: "Bajaj Geyser Repair", description: "Bajaj geyser service" },
  { slug: "havells-geyser-repair-vadodara", title: "Havells Geyser Repair", description: "Havells geyser service" },
  { slug: "water-tank-installation-vadodara", title: "Water Tank Installation", description: "Water tank installation" },
  { slug: "overhead-tank-vadodara", title: "Overhead Tank", description: "Overhead tank services" },
  { slug: "water-pump-repair-vadodara", title: "Water Pump Repair", description: "Water pump repair" },
  { slug: "submersible-pump-vadodara", title: "Submersible Pump", description: "Submersible pump services" },
  { slug: "water-tank-cleaning-vadodara", title: "Water Tank Cleaning", description: "Tank cleaning service" },
  { slug: "underground-tank-vadodara", title: "Underground Tank", description: "Underground tank work" },
  { slug: "borewell-pump-vadodara", title: "Borewell Pump", description: "Borewell pump services" },
  { slug: "motor-repair-vadodara", title: "Motor Repair", description: "Water motor repair" },
  { slug: "pressure-pump-vadodara", title: "Pressure Pump", description: "Pressure pump installation" },
  { slug: "toilet-repair-vadodara", title: "Toilet Repair", description: "Toilet repair services" },
  { slug: "toilet-installation-vadodara", title: "Toilet Installation", description: "Toilet installation" },
  { slug: "commode-installation-vadodara", title: "Commode Installation", description: "Commode fitting" },
  { slug: "western-toilet-vadodara", title: "Western Toilet", description: "Western toilet installation" },
  { slug: "toilet-blockage-vadodara", title: "Toilet Blockage", description: "Toilet blockage clearing" },
  { slug: "flush-tank-repair-vadodara", title: "Flush Tank Repair", description: "Flush tank repair" },
  { slug: "basin-installation-vadodara", title: "Basin Installation", description: "Wash basin fitting" },
  { slug: "bathroom-fitting-vadodara", title: "Bathroom Fitting", description: "Complete bathroom fitting" },
  { slug: "shower-installation-vadodara", title: "Shower Installation", description: "Shower installation" },
  { slug: "ro-service-vadodara", title: "RO Service", description: "RO water purifier service" },
  { slug: "water-purifier-repair-vadodara", title: "Water Purifier Repair", description: "Water purifier repair" },
  { slug: "ro-installation-vadodara", title: "RO Installation", description: "RO installation service" },
  { slug: "kent-ro-service-vadodara", title: "Kent RO Service", description: "Kent RO service" },
  { slug: "aquaguard-service-vadodara", title: "Aquaguard Service", description: "Aquaguard repair" },
  { slug: "cpvc-pipe-fitting-vadodara", title: "CPVC Pipe Fitting", description: "CPVC pipe work" },
  { slug: "pvc-pipe-vadodara", title: "PVC Pipe", description: "PVC pipe installation" },
  { slug: "gi-pipe-vadodara", title: "GI Pipe", description: "GI pipe fitting" },
  { slug: "concealed-plumbing-vadodara", title: "Concealed Plumbing", description: "Concealed pipe work" },
  { slug: "pipe-leakage-vadodara", title: "Pipe Leakage", description: "Pipe leakage repair" },
];

// ============ CARPENTER KEYWORDS (70+) ============
export const carpenterKeywords = [
  { slug: "carpenter-vadodara", title: "Carpenter", description: "Professional carpenter services" },
  { slug: "furniture-maker-vadodara", title: "Furniture Maker", description: "Custom furniture maker" },
  { slug: "carpentry-work-vadodara", title: "Carpentry Work", description: "All carpentry services" },
  { slug: "woodwork-vadodara", title: "Woodwork", description: "All woodwork services" },
  { slug: "carpenter-near-me-vadodara", title: "Carpenter Near Me", description: "Local carpenter nearby" },
  { slug: "best-carpenter-vadodara", title: "Best Carpenter", description: "Top rated carpenters" },
  { slug: "interior-carpenter-vadodara", title: "Interior Carpenter", description: "Interior carpentry work" },
  { slug: "suthar-vadodara", title: "Suthar", description: "Professional suthar services" },
  { slug: "suthar-kam-vadodara", title: "Suthar Kam", description: "Suthar carpentry work" },
  { slug: "modular-kitchen-vadodara", title: "Modular Kitchen", description: "Modular kitchen design" },
  { slug: "kitchen-design-vadodara", title: "Kitchen Design", description: "Kitchen design services" },
  { slug: "kitchen-cabinet-vadodara", title: "Kitchen Cabinet", description: "Kitchen cabinet making" },
  { slug: "modular-kitchen-price-vadodara", title: "Modular Kitchen Price", description: "Modular kitchen rates" },
  { slug: "modular-kitchen-design-vadodara", title: "Modular Kitchen Design", description: "Kitchen design ideas" },
  { slug: "kitchen-trolley-vadodara", title: "Kitchen Trolley", description: "Kitchen trolley making" },
  { slug: "kitchen-platform-vadodara", title: "Kitchen Platform", description: "Kitchen platform work" },
  { slug: "l-shaped-kitchen-vadodara", title: "L Shaped Kitchen", description: "L shaped kitchen design" },
  { slug: "u-shaped-kitchen-vadodara", title: "U Shaped Kitchen", description: "U shaped kitchen design" },
  { slug: "parallel-kitchen-vadodara", title: "Parallel Kitchen", description: "Parallel kitchen design" },
  { slug: "island-kitchen-vadodara", title: "Island Kitchen", description: "Island kitchen design" },
  { slug: "wardrobe-vadodara", title: "Wardrobe", description: "Wardrobe design and making" },
  { slug: "wardrobe-design-vadodara", title: "Wardrobe Design", description: "Custom wardrobe design" },
  { slug: "sliding-wardrobe-vadodara", title: "Sliding Wardrobe", description: "Sliding wardrobe design" },
  { slug: "walk-in-wardrobe-vadodara", title: "Walk In Wardrobe", description: "Walk-in closet design" },
  { slug: "bedroom-wardrobe-vadodara", title: "Bedroom Wardrobe", description: "Bedroom wardrobe work" },
  { slug: "wardrobe-price-vadodara", title: "Wardrobe Price", description: "Wardrobe rates" },
  { slug: "cupboard-vadodara", title: "Cupboard", description: "Cupboard making" },
  { slug: "storage-unit-vadodara", title: "Storage Unit", description: "Storage unit design" },
  { slug: "shoe-rack-vadodara", title: "Shoe Rack", description: "Shoe rack making" },
  { slug: "bookshelf-vadodara", title: "Bookshelf", description: "Bookshelf design" },
  { slug: "tv-unit-vadodara", title: "TV Unit", description: "TV unit design and making" },
  { slug: "tv-cabinet-vadodara", title: "TV Cabinet", description: "TV cabinet services" },
  { slug: "tv-unit-design-vadodara", title: "TV Unit Design", description: "TV unit ideas" },
  { slug: "entertainment-unit-vadodara", title: "Entertainment Unit", description: "Entertainment center" },
  { slug: "wall-unit-vadodara", title: "Wall Unit", description: "Wall unit design" },
  { slug: "door-fitting-vadodara", title: "Door Fitting", description: "Door fitting and installation" },
  { slug: "window-fitting-vadodara", title: "Window Fitting", description: "Window fitting services" },
  { slug: "wooden-door-vadodara", title: "Wooden Door", description: "Wooden door making" },
  { slug: "main-door-design-vadodara", title: "Main Door Design", description: "Main door design" },
  { slug: "door-frame-vadodara", title: "Door Frame", description: "Door frame work" },
  { slug: "door-repair-vadodara", title: "Door Repair", description: "Door repair service" },
  { slug: "flush-door-vadodara", title: "Flush Door", description: "Flush door installation" },
  { slug: "panel-door-vadodara", title: "Panel Door", description: "Panel door making" },
  { slug: "furniture-repair-vadodara", title: "Furniture Repair", description: "Furniture repair services" },
  { slug: "custom-furniture-vadodara", title: "Custom Furniture", description: "Custom furniture design" },
  { slug: "office-furniture-vadodara", title: "Office Furniture", description: "Office furniture making" },
  { slug: "bed-design-vadodara", title: "Bed Design", description: "Custom bed design" },
  { slug: "double-bed-vadodara", title: "Double Bed", description: "Double bed making" },
  { slug: "king-size-bed-vadodara", title: "King Size Bed", description: "King size bed design" },
  { slug: "sofa-set-vadodara", title: "Sofa Set", description: "Sofa set making" },
  { slug: "dining-table-vadodara", title: "Dining Table", description: "Dining table design" },
  { slug: "study-table-vadodara", title: "Study Table", description: "Study table making" },
  { slug: "center-table-vadodara", title: "Center Table", description: "Center table design" },
  { slug: "dressing-table-vadodara", title: "Dressing Table", description: "Dressing table making" },
  { slug: "computer-table-vadodara", title: "Computer Table", description: "Computer table design" },
  { slug: "office-table-vadodara", title: "Office Table", description: "Office desk making" },
  { slug: "wood-polish-vadodara", title: "Wood Polish", description: "Wood polishing services" },
  { slug: "furniture-polish-vadodara", title: "Furniture Polish", description: "Furniture polish work" },
  { slug: "sofa-repair-vadodara", title: "Sofa Repair", description: "Sofa repair services" },
  { slug: "sofa-reupholstery-vadodara", title: "Sofa Reupholstery", description: "Sofa reupholstery work" },
  { slug: "chair-repair-vadodara", title: "Chair Repair", description: "Chair repair service" },
  { slug: "laminate-work-vadodara", title: "Laminate Work", description: "Laminate application" },
  { slug: "veneer-work-vadodara", title: "Veneer Work", description: "Veneer application" },
  { slug: "plywood-work-vadodara", title: "Plywood Work", description: "Plywood work services" },
  { slug: "wooden-partition-vadodara", title: "Wooden Partition", description: "Wooden partition work" },
  { slug: "wooden-flooring-vadodara", title: "Wooden Flooring", description: "Wooden flooring installation" },
  { slug: "mandir-design-vadodara", title: "Mandir Design", description: "Wooden mandir making" },
  { slug: "pooja-unit-vadodara", title: "Pooja Unit", description: "Pooja unit design" },
  { slug: "crockery-unit-vadodara", title: "Crockery Unit", description: "Crockery unit making" },
];

// ============ FABRICATION KEYWORDS (60+) ============
export const fabricationKeywords = [
  { slug: "fabrication-vadodara", title: "Fabrication", description: "Metal fabrication services" },
  { slug: "steel-fabrication-vadodara", title: "Steel Fabrication", description: "Steel fabrication work" },
  { slug: "metal-fabrication-vadodara", title: "Metal Fabrication", description: "Metal fabrication services" },
  { slug: "fabrication-near-me-vadodara", title: "Fabrication Near Me", description: "Local fabrication work" },
  { slug: "best-fabricator-vadodara", title: "Best Fabricator", description: "Top fabrication services" },
  { slug: "welding-vadodara", title: "Welding", description: "Welding services" },
  { slug: "welding-work-vadodara", title: "Welding Work", description: "Professional welding work" },
  { slug: "welder-vadodara", title: "Welder", description: "Expert welders" },
  { slug: "ms-fabrication-vadodara", title: "MS Fabrication", description: "MS fabrication work" },
  { slug: "ss-fabrication-vadodara", title: "SS Fabrication", description: "SS fabrication work" },
  { slug: "lohedar-vadodara", title: "Lohedar", description: "Professional lohedar" },
  { slug: "lohedar-kam-vadodara", title: "Lohedar Kam", description: "Metal work services" },
  { slug: "gate-fabrication-vadodara", title: "Gate Fabrication", description: "Gate fabrication work" },
  { slug: "main-gate-vadodara", title: "Main Gate", description: "Main gate design and making" },
  { slug: "ms-gate-vadodara", title: "MS Gate", description: "MS gate fabrication" },
  { slug: "ss-gate-vadodara", title: "SS Gate", description: "Stainless steel gate" },
  { slug: "iron-gate-vadodara", title: "Iron Gate", description: "Iron gate making" },
  { slug: "designer-gate-vadodara", title: "Designer Gate", description: "Designer gate work" },
  { slug: "sliding-gate-vadodara", title: "Sliding Gate", description: "Sliding gate installation" },
  { slug: "swing-gate-vadodara", title: "Swing Gate", description: "Swing gate making" },
  { slug: "automatic-gate-vadodara", title: "Automatic Gate", description: "Automatic gate system" },
  { slug: "collapsible-gate-vadodara", title: "Collapsible Gate", description: "Collapsible gate fabrication" },
  { slug: "gate-price-vadodara", title: "Gate Price", description: "Gate rates in Vadodara" },
  { slug: "window-grill-vadodara", title: "Window Grill", description: "Window grill fabrication" },
  { slug: "safety-grill-vadodara", title: "Safety Grill", description: "Safety grill installation" },
  { slug: "balcony-grill-vadodara", title: "Balcony Grill", description: "Balcony grill work" },
  { slug: "door-grill-vadodara", title: "Door Grill", description: "Door grill making" },
  { slug: "ms-grill-vadodara", title: "MS Grill", description: "MS grill fabrication" },
  { slug: "ss-grill-vadodara", title: "SS Grill", description: "SS grill work" },
  { slug: "designer-grill-vadodara", title: "Designer Grill", description: "Designer grill patterns" },
  { slug: "safety-door-vadodara", title: "Safety Door", description: "Safety door installation" },
  { slug: "mosquito-net-vadodara", title: "Mosquito Net", description: "Mosquito net for windows" },
  { slug: "ss-railing-vadodara", title: "SS Railing", description: "Stainless steel railing" },
  { slug: "ms-railing-vadodara", title: "MS Railing", description: "MS railing fabrication" },
  { slug: "glass-railing-vadodara", title: "Glass Railing", description: "Glass railing installation" },
  { slug: "balcony-railing-vadodara", title: "Balcony Railing", description: "Balcony railing work" },
  { slug: "staircase-railing-vadodara", title: "Staircase Railing", description: "Staircase railing design" },
  { slug: "handrail-vadodara", title: "Handrail", description: "Handrail installation" },
  { slug: "railing-design-vadodara", title: "Railing Design", description: "Railing design ideas" },
  { slug: "ss-304-railing-vadodara", title: "SS 304 Railing", description: "SS 304 grade railing" },
  { slug: "iron-staircase-vadodara", title: "Iron Staircase", description: "Iron staircase fabrication" },
  { slug: "spiral-staircase-vadodara", title: "Spiral Staircase", description: "Spiral staircase design" },
  { slug: "steel-staircase-vadodara", title: "Steel Staircase", description: "Steel staircase making" },
  { slug: "staircase-design-vadodara", title: "Staircase Design", description: "Staircase design ideas" },
  { slug: "shed-fabrication-vadodara", title: "Shed Fabrication", description: "Shed structure fabrication" },
  { slug: "industrial-shed-vadodara", title: "Industrial Shed", description: "Industrial shed construction" },
  { slug: "parking-shed-vadodara", title: "Parking Shed", description: "Parking shed making" },
  { slug: "car-parking-shed-vadodara", title: "Car Parking Shed", description: "Car parking structure" },
  { slug: "polycarbonate-shed-vadodara", title: "Polycarbonate Shed", description: "Polycarbonate roofing" },
  { slug: "canopy-vadodara", title: "Canopy", description: "Canopy installation" },
  { slug: "awning-vadodara", title: "Awning", description: "Awning fabrication" },
  { slug: "pergola-vadodara", title: "Pergola", description: "Pergola structure" },
  { slug: "rolling-shutter-vadodara", title: "Rolling Shutter", description: "Rolling shutter installation" },
  { slug: "tank-fabrication-vadodara", title: "Tank Fabrication", description: "Tank fabrication services" },
  { slug: "structural-fabrication-vadodara", title: "Structural Fabrication", description: "Structural steel work" },
  { slug: "industrial-fabrication-vadodara", title: "Industrial Fabrication", description: "Industrial fabrication" },
  { slug: "duct-fabrication-vadodara", title: "Duct Fabrication", description: "Duct making work" },
  { slug: "fire-escape-vadodara", title: "Fire Escape", description: "Fire escape staircase" },
];

// ============ SOLAR KEYWORDS (40+) ============
export const solarKeywords = [
  { slug: "solar-installation-vadodara", title: "Solar Installation", description: "Solar system installation" },
  { slug: "solar-panel-installation-vadodara", title: "Solar Panel Installation", description: "Solar panel fitting" },
  { slug: "rooftop-solar-vadodara", title: "Rooftop Solar", description: "Rooftop solar installation" },
  { slug: "home-solar-vadodara", title: "Home Solar", description: "Home solar system" },
  { slug: "residential-solar-vadodara", title: "Residential Solar", description: "Residential solar setup" },
  { slug: "commercial-solar-vadodara", title: "Commercial Solar", description: "Commercial solar systems" },
  { slug: "industrial-solar-vadodara", title: "Industrial Solar", description: "Industrial solar solutions" },
  { slug: "solar-power-plant-vadodara", title: "Solar Power Plant", description: "Solar power plant setup" },
  { slug: "solar-system-vadodara", title: "Solar System", description: "Complete solar system" },
  { slug: "best-solar-company-vadodara", title: "Best Solar Company", description: "Top solar company" },
  { slug: "solar-near-me-vadodara", title: "Solar Near Me", description: "Local solar installer" },
  { slug: "on-grid-solar-vadodara", title: "On Grid Solar", description: "On-grid solar systems" },
  { slug: "off-grid-solar-vadodara", title: "Off Grid Solar", description: "Off-grid solar systems" },
  { slug: "hybrid-solar-vadodara", title: "Hybrid Solar", description: "Hybrid solar system" },
  { slug: "1kw-solar-vadodara", title: "1kW Solar", description: "1kW solar system" },
  { slug: "2kw-solar-vadodara", title: "2kW Solar", description: "2kW solar system" },
  { slug: "3kw-solar-vadodara", title: "3kW Solar", description: "3kW solar system" },
  { slug: "5kw-solar-vadodara", title: "5kW Solar", description: "5kW solar system" },
  { slug: "10kw-solar-vadodara", title: "10kW Solar", description: "10kW solar system" },
  { slug: "solar-price-vadodara", title: "Solar Price", description: "Solar system prices" },
  { slug: "solar-panel-price-vadodara", title: "Solar Panel Price", description: "Solar panel rates" },
  { slug: "solar-cost-vadodara", title: "Solar Cost", description: "Solar installation cost" },
  { slug: "solar-subsidy-vadodara", title: "Solar Subsidy", description: "Government solar subsidy" },
  { slug: "pm-surya-ghar-vadodara", title: "PM Surya Ghar", description: "PM Surya Ghar Yojana" },
  { slug: "solar-loan-vadodara", title: "Solar Loan", description: "Solar financing options" },
  { slug: "net-metering-vadodara", title: "Net Metering", description: "Net metering setup" },
  { slug: "solar-maintenance-vadodara", title: "Solar Maintenance", description: "Solar system maintenance" },
  { slug: "solar-panel-cleaning-vadodara", title: "Solar Panel Cleaning", description: "Solar panel cleaning service" },
  { slug: "solar-amc-vadodara", title: "Solar AMC", description: "Solar annual maintenance contract" },
  { slug: "solar-inverter-repair-vadodara", title: "Solar Inverter Repair", description: "Solar inverter repair" },
  { slug: "solar-system-repair-vadodara", title: "Solar System Repair", description: "Solar system repair" },
  { slug: "solar-panel-repair-vadodara", title: "Solar Panel Repair", description: "Solar panel repair" },
  { slug: "solar-battery-vadodara", title: "Solar Battery", description: "Solar battery services" },
  { slug: "solar-system-checkup-vadodara", title: "Solar System Checkup", description: "Solar system health check" },
  { slug: "solar-plant-maintenance-vadodara", title: "Solar Plant Maintenance", description: "Solar plant maintenance" },
  { slug: "tata-solar-vadodara", title: "Tata Solar", description: "Tata solar panels" },
  { slug: "adani-solar-vadodara", title: "Adani Solar", description: "Adani solar system" },
  { slug: "waaree-solar-vadodara", title: "Waaree Solar", description: "Waaree solar panels" },
  { slug: "luminous-solar-vadodara", title: "Luminous Solar", description: "Luminous solar" },
  { slug: "solar-water-heater-vadodara", title: "Solar Water Heater", description: "Solar water heating" },
  { slug: "solar-geyser-vadodara", title: "Solar Geyser", description: "Solar geyser installation" },
];

// Combine all keywords with category
export const allKeywords = [
  ...paintingKeywords.map(k => ({ ...k, category: "painting" as const })),
  ...civilKeywords.map(k => ({ ...k, category: "civil" as const })),
  ...plumbingKeywords.map(k => ({ ...k, category: "plumbing" as const })),
  ...carpenterKeywords.map(k => ({ ...k, category: "carpenter" as const })),
  ...fabricationKeywords.map(k => ({ ...k, category: "fabrication" as const })),
  ...solarKeywords.map(k => ({ ...k, category: "solar" as const })),
];

// Area Keywords (for [slug] route - generates URLs like /services-alkapuri-vadodara)
export const areaKeywords = [
  { slug: "services-alkapuri-vadodara", areaName: "Alkapuri" },
  { slug: "services-gotri-vadodara", areaName: "Gotri" },
  { slug: "services-manjalpur-vadodara", areaName: "Manjalpur" },
  { slug: "services-akota-vadodara", areaName: "Akota" },
  { slug: "services-bhayli-vadodara", areaName: "Bhayli" },
  { slug: "services-karelibaug-vadodara", areaName: "Karelibaug" },
  { slug: "services-waghodia-road-vadodara", areaName: "Waghodia Road" },
  { slug: "services-makarpura-vadodara", areaName: "Makarpura" },
  { slug: "services-chhani-vadodara", areaName: "Chhani" },
  { slug: "services-harni-vadodara", areaName: "Harni" },
  { slug: "services-fatehgunj-vadodara", areaName: "Fatehgunj" },
  { slug: "services-gorwa-vadodara", areaName: "Gorwa" },
  { slug: "services-sayajigunj-vadodara", areaName: "Sayajigunj" },
  { slug: "services-tarsali-vadodara", areaName: "Tarsali" },
  { slug: "services-ajwa-road-vadodara", areaName: "Ajwa Road" },
  { slug: "services-subhanpura-vadodara", areaName: "Subhanpura" },
  { slug: "services-tandalja-vadodara", areaName: "Tandalja" },
  { slug: "services-sama-vadodara", areaName: "Sama" },
  { slug: "services-vasna-vadodara", areaName: "Vasna" },
  { slug: "services-nizampura-vadodara", areaName: "Nizampura" },
  { slug: "services-atladara-vadodara", areaName: "Atladara" },
  { slug: "services-sevasi-vadodara", areaName: "Sevasi" },
  { slug: "services-vadsar-vadodara", areaName: "Vadsar" },
  { slug: "services-race-course-vadodara", areaName: "Race Course" },
  { slug: "services-pratap-nagar-vadodara", areaName: "Pratap Nagar" },
  { slug: "services-ellora-park-vadodara", areaName: "Ellora Park" },
  { slug: "services-new-vip-road-vadodara", areaName: "New VIP Road" },
  { slug: "services-old-padra-road-vadodara", areaName: "Old Padra Road" },
  { slug: "services-maneja-vadodara", areaName: "Maneja" },
  { slug: "services-gotri-road-vadodara", areaName: "Gotri Road" },
  { slug: "services-kalali-vadodara", areaName: "Kalali" },
  { slug: "services-diwalipura-vadodara", areaName: "Diwalipura" },
  { slug: "services-raopura-vadodara", areaName: "Raopura" },
  { slug: "services-wadi-vadodara", areaName: "Wadi" },
  { slug: "services-danteshwar-vadodara", areaName: "Danteshwar" },
  { slug: "services-jetalpur-vadodara", areaName: "Jetalpur" },
  { slug: "services-sindhrot-vadodara", areaName: "Sindhrot" },
  { slug: "services-laxmipura-vadodara", areaName: "Laxmipura" },
  { slug: "services-navapura-vadodara", areaName: "Navapura" },
  { slug: "services-panigate-vadodara", areaName: "Panigate" },
];

// Vadodara Areas (40 areas)
export const vadodaraAreas = [
  { slug: "alkapuri", name: "Alkapuri" },
  { slug: "gotri", name: "Gotri" },
  { slug: "manjalpur", name: "Manjalpur" },
  { slug: "akota", name: "Akota" },
  { slug: "bhayli", name: "Bhayli" },
  { slug: "karelibaug", name: "Karelibaug" },
  { slug: "waghodia-road", name: "Waghodia Road" },
  { slug: "makarpura", name: "Makarpura" },
  { slug: "chhani", name: "Chhani" },
  { slug: "harni", name: "Harni" },
  { slug: "fatehgunj", name: "Fatehgunj" },
  { slug: "gorwa", name: "Gorwa" },
  { slug: "sayajigunj", name: "Sayajigunj" },
  { slug: "tarsali", name: "Tarsali" },
  { slug: "ajwa-road", name: "Ajwa Road" },
  { slug: "subhanpura", name: "Subhanpura" },
  { slug: "tandalja", name: "Tandalja" },
  { slug: "sama", name: "Sama" },
  { slug: "vasna", name: "Vasna" },
  { slug: "nizampura", name: "Nizampura" },
  { slug: "atladara", name: "Atladara" },
  { slug: "sevasi", name: "Sevasi" },
  { slug: "vadsar", name: "Vadsar" },
  { slug: "race-course", name: "Race Course" },
  { slug: "pratap-nagar", name: "Pratap Nagar" },
  { slug: "ellora-park", name: "Ellora Park" },
  { slug: "new-vip-road", name: "New VIP Road" },
  { slug: "old-padra-road", name: "Old Padra Road" },
  { slug: "maneja", name: "Maneja" },
  { slug: "gotri-road", name: "Gotri Road" },
  { slug: "kalali", name: "Kalali" },
  { slug: "diwalipura", name: "Diwalipura" },
  { slug: "raopura", name: "Raopura" },
  { slug: "wadi", name: "Wadi" },
  { slug: "danteshwar", name: "Danteshwar" },
  { slug: "jetalpur", name: "Jetalpur" },
  { slug: "sindhrot", name: "Sindhrot" },
  { slug: "laxmipura", name: "Laxmipura" },
  { slug: "navapura", name: "Navapura" },
  { slug: "panigate", name: "Panigate" },
];

export type ServiceCategory = "painting" | "civil" | "plumbing" | "carpenter" | "fabrication" | "solar";

export const categoryConfig: Record<ServiceCategory, { 
  title: string; 
  color: string; 
  gradient: string;
  icon: string;
  services: string[];
}> = {
  painting: {
    title: "POP & Painting",
    color: "orange",
    gradient: "from-orange-500 to-orange-600",
    icon: "Paintbrush",
    services: ["POP False Ceiling", "Wall Painting", "Texture Painting", "Interior Painting", "Exterior Painting", "Gypsum Ceiling"],
  },
  civil: {
    title: "Civil Work",
    color: "amber",
    gradient: "from-amber-500 to-amber-600",
    icon: "Hammer",
    services: ["Tile Fitting", "Waterproofing", "Bathroom Renovation", "Kitchen Renovation", "Flooring", "Plastering"],
  },
  plumbing: {
    title: "Plumbing",
    color: "blue",
    gradient: "from-blue-500 to-blue-600",
    icon: "Wrench",
    services: ["Pipe Fitting", "Leak Repair", "Drainage Work", "Geyser Repair", "Bathroom Plumbing", "Water Tank"],
  },
  carpenter: {
    title: "Carpenter & Furniture",
    color: "green",
    gradient: "from-green-600 to-green-700",
    icon: "Sofa",
    services: ["Modular Kitchen", "Wardrobe", "TV Unit", "Door Fitting", "Furniture Repair", "Wood Polish"],
  },
  fabrication: {
    title: "Fabrication & Welding",
    color: "gray",
    gradient: "from-gray-600 to-gray-700",
    icon: "Settings",
    services: ["Gate Fabrication", "Window Grill", "SS Railing", "Welding Work", "Shed Fabrication", "Staircase"],
  },
  solar: {
    title: "Solar Services",
    color: "yellow",
    gradient: "from-yellow-500 to-orange-500",
    icon: "Sun",
    services: ["Solar Installation", "Solar Cleaning", "Solar AMC", "Inverter Repair", "Panel Repair", "Net Metering"],
  },
};

// Service images for sliders (category-based Unsplash images)
export const categoryImages: Record<ServiceCategory, { src: string; alt: string }[]> = {
  painting: [
    { src: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800&q=80", alt: "POP False Ceiling Work" },
    { src: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&q=80", alt: "Wall Painting Service" },
    { src: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80", alt: "Texture Paint Design" },
    { src: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80", alt: "Interior Painting" },
  ],
  civil: [
    { src: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80", alt: "Tile Fitting Work" },
    { src: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80", alt: "Bathroom Renovation" },
    { src: "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80", alt: "Floor Tile Installation" },
    { src: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80", alt: "Modern Flooring" },
  ],
  plumbing: [
    { src: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800&q=80", alt: "Pipe Fitting Work" },
    { src: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80", alt: "Bathroom Plumbing" },
    { src: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80", alt: "Geyser Installation" },
    { src: "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80", alt: "Kitchen Plumbing" },
  ],
  carpenter: [
    { src: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80", alt: "Modular Kitchen Design" },
    { src: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80", alt: "Wardrobe Installation" },
    { src: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80", alt: "Custom Furniture" },
    { src: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=800&q=80", alt: "TV Unit Design" },
  ],
  fabrication: [
    { src: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80", alt: "Main Gate Design" },
    { src: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80", alt: "SS Railing Work" },
    { src: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=800&q=80", alt: "Window Grill" },
    { src: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80", alt: "Metal Fabrication" },
  ],
  solar: [
    { src: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80", alt: "Rooftop Solar Installation" },
    { src: "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800&q=80", alt: "Solar Panel Setup" },
    { src: "https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?w=800&q=80", alt: "Solar Energy System" },
    { src: "https://images.unsplash.com/photo-1497440001374-f26997328c1b?w=800&q=80", alt: "Clean Energy Solution" },
  ],
};
